# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: en-US
title: Ryandinho
email: ryan@ryandinho.me
description: Cybersecurity Practioner
baseurl: /
url: https://ryanestes.github.io
author:
  name: Ryan Estes
  twitter: _RuMmE
  picture: /assets/images/avatar.jpg
twitter_username: _RuMmE
github_username: ryanestes
logo: /assets/images/avatar.jpg
search: false
search_full_content: false
search_provider: # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false
  
# Extras added by me
disqus:
  shortname: ryandinho
google_analytics: UA-142299262-1
linkedin_username: ryanestes5

# Build settings
markdown: kramdown
remote_theme: mmistakes/jekyll-theme-basically-basic@1.4.5
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
